pipeline {
    agent any
    parameters {
        choice(name: 'NUMBER',
            choices: [10,20,30,40,50,60,70,80,90],
            description: 'Select the value for F(n) for the Fibonacci sequence.')
    }
    options {
        buildDiscarder(logRotator(daysToKeepStr: '10', numToKeepStr: '10'))
        timeout(time: 12, unit: 'HOURS')
        timestamps()
    }
    triggers {
        cron '@midnight'
    }
    stages {
        stage('Make executable') {
            steps {
                sh 'chmod +x ./Ch03/03_03-run-scripts-from-the-pipeline/fibonacci.sh'
            }
        }
        stage('Relative path') {
            steps {
                sh "./Ch03/03_03-run-scripts-from-the-pipeline/fibonacci.sh ${env.NUMBER}"
            }
        }
        stage('Full path') {
            steps {
                script {
                    def fullPath = sh(script: 'pwd', returnStdout: true).trim()
                    sh "./Ch03/03_03-run-scripts-from-the-pipeline/fibonacci.sh ${env.NUMBER}"
                    echo "Full path: ${fullPath}/Ch03/03_03-run-scripts-from-the-pipeline/fibonacci.sh"
                }
            }
        }
        stage('Change directory') {
            steps {
                dir("./Ch03/03_03-run-scripts-from-the-pipeline/") {
                    sh "./fibonacci.sh ${env.NUMBER}"
                }
            }
        }
    }
}
